# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico
darkmode: true


# Personal info
name: Shilpa Bhandari
title: Data Science Intern at Ernst and Young 
email: parasianshilpa@gmail.com
# Social links
github_username: shibha20
instagram_username: 77_parasian
linkedin_username: astroshilpa


# About Section
# about_title: About Me
about_profile_image: profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Shilpa Bhandari. I am a senior at Youngstown State University pursuing Computer Science and Mathematics. 
  I am skilled in: <mark>Python</mark>, <mark>Jave</mark>,<mark>SQL</mark>, <mark>C++</mark>,<mark>Office 365</mark>, <mark>LaTeX</mark>,<mark>MATLAB</mark>, 
  <mark>Data Analysis</mark>, <mark>Design Thinking</mark>, <mark>Storytelling</mark>, and <mark>Eating Momo</mark>.
  
resume_section_education: true
resume_section_experience: true
resume_section_projects: true

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs 
  Alongside my interests in Data Science and Machine Learning, some of my other interests and hobbies are:
   - International Business
   - Volunteering 
   - <a href="https://www.flickr.com/photos/189095843@N05/"> Travel & Photography </a> 
   - Social Entrepreneurship 
 
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

theme: jekyll-theme-slate
